plugins {
    id 'org.springframework.boot' version '4.2.0-M2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id "com.google.osdetector" version "1.7.3"
    id("io.freefair.lombok") version "9.5.0"
}

project.ext {
    publishRepo = "https://maven.pkg.github.com/reportportal/service-jobs"
    releaseMode = project.hasProperty("releaseMode")
}

def scriptsUrl = 'https://raw.githubusercontent.com/reportportal/gradle-scripts/' + (releaseMode ? '5.14.0' : 'develop')

apply from: "$scriptsUrl/build-commons.gradle"
apply from: "$scriptsUrl/build-info.gradle"
apply from: "$scriptsUrl/release-service.gradle"
apply from: "$scriptsUrl/signing.gradle"

java {
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    options.encoding = "UTF-8"
    options.compilerArgs << "-parameters"
}

wrapper {
    gradleVersion = '9.3.1'
}

bootJar {
    project.hasProperty('gcp') ? getArchiveFileName().set('app.jar') : archiveClassifier.set('exec')
}
jar.enabled = true
jar.archiveClassifier.set('')

repositories {
    mavenCentral { url = "https://repo1.maven.org/maven2" }
    maven { url = 'https://repo.spring.io/libs-milestone' }
    maven { url = 'https://jitpack.io' }
}

processResources {
    dependsOn(gitInfo)
    filesMatching('application.properties') {
        expand(project.properties)
    }
}

dependencies {

    // ── application dependencies ──────────────────────────────────────────
    implementation "org.json:json:20260814"
    implementation "net.javacrumbs.shedlock:shedlock-spring:7.8.0"
    implementation "net.javacrumbs.shedlock:shedlock-provider-jdbc-template:7.8.0"
    implementation 'org.apache.commons:commons-lang3'
    implementation "org.apache.commons:commons-compress:1.28.0"

    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation "org.apache.opendal:opendal:0.50.6"
    implementation "org.apache.opendal:opendal:0.50.6:$osdetector.classifier"

    implementation "com.rabbitmq:http-client:5.7.0"

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}

test {
    useJUnitPlatform()
}

publish.dependsOn build
publish.mustRunAfter build

tasks.preTagCommit.enabled = false
tasks.updateVersion.enabled = false
tasks.commitNewVersion.enabled = false
