version=5.15.1
description=EPAM Report portal. Service jobs
dockerServerUrl=unix:///var/run/docker.sock
dockerPrepareEnvironment=
dockerJavaOpts=-Xmx512m -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=70 -Djava.security.egd=file:/dev/./urandom

shedlockVersion=7.8.0
commonsCompressVersion=1.28.0
guavaVersion=33.7.2-jre
jsonVersion=20260814
opendalVersion=0.49.0
rabbitmqHttpClientVersion=5.7.0
